import type {
  AlertItem,
  Cluster,
  Datastore,
  Host,
  Network,
  VirtualMachine,
} from "./types";
import { idleConsole } from "./console-engine";

function hist(base: number): number[] {
  return Array.from({ length: 24 }, (_, i) => {
    const n = base + Math.sin(i / 2.4) * 7 + Math.cos(i / 5) * 3;
    return Math.round(Math.min(96, Math.max(4, n)));
  });
}

export const DATACENTER_NAME = "Aether Datacenter";
export const VCENTER_HOST = "vcenter.aether.lab";

export const clusters: Cluster[] = [
  { id: "cl-prod", name: "Production", ha: true, drs: true },
  { id: "cl-lab", name: "Lab", ha: false, drs: true },
];

export const hosts: Host[] = [
  {
    id: "h1",
    name: "esx-prod-01.aether.lab",
    clusterId: "cl-prod",
    cpuCores: 64,
    cpuMhz: 2500,
    memoryGb: 512,
    version: "Aether ESX 8.0 U3",
    state: "connected",
    cpuUsage: 41,
    memUsage: 62,
    cpuHistory: hist(41),
    memHistory: hist(62),
    uptimeSec: 86400 * 47 + 3600 * 6,
    model: "Dell PowerEdge R760",
  },
  {
    id: "h2",
    name: "esx-prod-02.aether.lab",
    clusterId: "cl-prod",
    cpuCores: 64,
    cpuMhz: 2500,
    memoryGb: 512,
    version: "Aether ESX 8.0 U3",
    state: "connected",
    cpuUsage: 36,
    memUsage: 54,
    cpuHistory: hist(36),
    memHistory: hist(54),
    uptimeSec: 86400 * 47 + 3600 * 4,
    model: "Dell PowerEdge R760",
  },
  {
    id: "h3",
    name: "esx-prod-03.aether.lab",
    clusterId: "cl-prod",
    cpuCores: 48,
    cpuMhz: 2400,
    memoryGb: 384,
    version: "Aether ESX 8.0 U3",
    state: "connected",
    cpuUsage: 22,
    memUsage: 38,
    cpuHistory: hist(22),
    memHistory: hist(38),
    uptimeSec: 86400 * 18 + 3600 * 11,
    model: "HPE ProLiant DL380 Gen11",
  },
  {
    id: "h4",
    name: "esx-lab-01.aether.lab",
    clusterId: "cl-lab",
    cpuCores: 32,
    cpuMhz: 2300,
    memoryGb: 256,
    version: "Aether ESX 8.0 U2",
    state: "connected",
    cpuUsage: 14,
    memUsage: 29,
    cpuHistory: hist(14),
    memHistory: hist(29),
    uptimeSec: 86400 * 9 + 3600 * 2,
    model: "Supermicro SYS-120U",
  },
];

export const datastores: Datastore[] = [
  { id: "ds-vsan", name: "vsanDatastore", type: "AetherFS", capacityGb: 49152, usedGb: 31200 },
  { id: "ds-nfs", name: "nfs-backup", type: "NFS", capacityGb: 20480, usedGb: 8192 },
  { id: "ds-lab", name: "local-nvme-lab", type: "VMFS", capacityGb: 4096, usedGb: 1280 },
];

export const networks: Network[] = [
  { id: "net-mgmt", name: "Management Network", type: "portgroup", vlan: 10, vswitch: "vSwitch0" },
  { id: "net-vm", name: "VM Network", type: "distributed", vlan: 20, vswitch: "dvSwitch-Prod" },
  { id: "net-stor", name: "Storage Network", type: "distributed", vlan: 30, vswitch: "dvSwitch-Prod" },
  { id: "net-dmz", name: "DMZ", type: "distributed", vlan: 40, vswitch: "dvSwitch-Edge" },
  { id: "net-vmotion", name: "vMotion", type: "distributed", vlan: 50, vswitch: "dvSwitch-Prod" },
];

function vm(partial: Omit<VirtualMachine, "cpuHistory" | "memHistory" | "consoleLines" | "booted" | "hardwareVersion" | "snapshots" | "currentSnapshotId" | "mac"> & Partial<VirtualMachine>): VirtualMachine {
  const cpuUsage = partial.cpuUsage ?? 0;
  const memUsage = partial.memUsage ?? 0;
  return {
    hardwareVersion: "AHW 21",
    snapshots: partial.snapshots ?? [],
    currentSnapshotId: partial.currentSnapshotId ?? null,
    consoleLines: partial.consoleLines ?? (partial.state === "poweredOn" || partial.state === "suspended" ? idleConsole(partial) : []),
    booted: partial.state === "poweredOn",
    mac: partial.mac ?? `00:50:56:a${partial.id.length}:${partial.id.slice(0, 2)}:${partial.id.slice(-2)}`,
    cpuHistory: partial.cpuHistory ?? hist(cpuUsage || 8),
    memHistory: partial.memHistory ?? hist(memUsage || 20),
    ...partial,
  } as VirtualMachine;
}

export const vms: VirtualMachine[] = [
  vm({
    id: "vm-web-01",
    name: "web-frontend-01",
    guestOs: "Ubuntu Linux (64-bit)",
    family: "linux",
    hostId: "h1",
    clusterId: "cl-prod",
    datastoreId: "ds-vsan",
    networkId: "net-vm",
    cpu: 4,
    memoryMb: 8192,
    diskGb: 80,
    state: "poweredOn",
    ip: "10.20.30.11",
    tools: "running",
    cpuUsage: 38,
    memUsage: 54,
    uptimeSec: 86400 * 12 + 3600 * 3,
    notes: "Primary nginx edge. Keep at N+1 with web-frontend-02.",
    folder: "Production",
    mac: "00:50:56:a1:1b:11",
  }),
  vm({
    id: "vm-web-02",
    name: "web-frontend-02",
    guestOs: "Ubuntu Linux (64-bit)",
    family: "linux",
    hostId: "h1",
    clusterId: "cl-prod",
    datastoreId: "ds-vsan",
    networkId: "net-vm",
    cpu: 4,
    memoryMb: 8192,
    diskGb: 80,
    state: "poweredOn",
    ip: "10.20.30.12",
    tools: "running",
    cpuUsage: 29,
    memUsage: 48,
    uptimeSec: 86400 * 12 + 3600 * 3,
    notes: "Secondary nginx edge.",
    folder: "Production",
    mac: "00:50:56:a1:1b:12",
  }),
  vm({
    id: "vm-db-01",
    name: "db-postgres-01",
    guestOs: "AlmaLinux 9 (64-bit)",
    family: "linux",
    hostId: "h1",
    clusterId: "cl-prod",
    datastoreId: "ds-vsan",
    networkId: "net-vm",
    cpu: 8,
    memoryMb: 32768,
    diskGb: 500,
    state: "poweredOn",
    ip: "10.20.30.40",
    tools: "running",
    cpuUsage: 61,
    memUsage: 78,
    uptimeSec: 86400 * 40,
    notes: "Primary Postgres 16. Snapshots nightly via backup job.",
    folder: "Production",
    mac: "00:50:56:a1:40:01",
    snapshots: [
      { id: "sn-db-1", name: "pre-16.4-upgrade", description: "Taken before minor upgrade", createdAt: Date.UTC(2026, 7, 12, 2, 0), parentId: null },
      { id: "sn-db-2", name: "post-upgrade-ok", description: "Verified 16.4", createdAt: Date.UTC(2026, 7, 12, 4, 30), parentId: "sn-db-1" },
    ],
    currentSnapshotId: "sn-db-2",
  }),
  vm({
    id: "vm-k8s-cp",
    name: "k8s-control-01",
    guestOs: "Ubuntu Linux (64-bit)",
    family: "linux",
    hostId: "h2",
    clusterId: "cl-prod",
    datastoreId: "ds-vsan",
    networkId: "net-vm",
    cpu: 4,
    memoryMb: 8192,
    diskGb: 60,
    state: "poweredOn",
    ip: "10.20.30.50",
    tools: "running",
    cpuUsage: 22,
    memUsage: 61,
    uptimeSec: 86400 * 21,
    notes: "Kubernetes control plane.",
    folder: "Production",
    mac: "00:50:56:a2:50:01",
  }),
  vm({
    id: "vm-k8s-w1",
    name: "k8s-worker-01",
    guestOs: "Ubuntu Linux (64-bit)",
    family: "linux",
    hostId: "h2",
    clusterId: "cl-prod",
    datastoreId: "ds-vsan",
    networkId: "net-vm",
    cpu: 8,
    memoryMb: 16384,
    diskGb: 120,
    state: "poweredOn",
    ip: "10.20.30.51",
    tools: "running",
    cpuUsage: 47,
    memUsage: 66,
    uptimeSec: 86400 * 21,
    notes: "",
    folder: "Production",
    mac: "00:50:56:a2:50:11",
  }),
  vm({
    id: "vm-k8s-w2",
    name: "k8s-worker-02",
    guestOs: "Ubuntu Linux (64-bit)",
    family: "linux",
    hostId: "h2",
    clusterId: "cl-prod",
    datastoreId: "ds-vsan",
    networkId: "net-vm",
    cpu: 8,
    memoryMb: 16384,
    diskGb: 120,
    state: "poweredOn",
    ip: "10.20.30.52",
    tools: "running",
    cpuUsage: 33,
    memUsage: 58,
    uptimeSec: 86400 * 21,
    notes: "",
    folder: "Production",
    mac: "00:50:56:a2:50:12",
  }),
  vm({
    id: "vm-win-dc",
    name: "win-dc-01",
    guestOs: "Microsoft Windows Server 2022 (64-bit)",
    family: "windows",
    hostId: "h3",
    clusterId: "cl-prod",
    datastoreId: "ds-vsan",
    networkId: "net-vm",
    cpu: 4,
    memoryMb: 8192,
    diskGb: 100,
    state: "poweredOn",
    ip: "10.20.30.10",
    tools: "running",
    cpuUsage: 12,
    memUsage: 44,
    uptimeSec: 86400 * 60,
    notes: "Domain controller. Do not snapshot while SYSVOL is busy.",
    folder: "Production",
    mac: "00:50:56:a3:10:01",
  }),
  vm({
    id: "vm-gitlab",
    name: "gitlab-01",
    guestOs: "Ubuntu Linux (64-bit)",
    family: "linux",
    hostId: "h3",
    clusterId: "cl-prod",
    datastoreId: "ds-vsan",
    networkId: "net-vm",
    cpu: 8,
    memoryMb: 16384,
    diskGb: 400,
    state: "suspended",
    ip: "10.20.30.70",
    tools: "notRunning",
    cpuUsage: 0,
    memUsage: 0,
    uptimeSec: 0,
    notes: "Suspended after weekend cutover. Resume Monday.",
    folder: "Production",
    mac: "00:50:56:a3:70:01",
    snapshots: [
      { id: "sn-gl-1", name: "before-16.11", description: "", createdAt: Date.UTC(2026, 6, 2, 22, 0), parentId: null },
      { id: "sn-gl-2", name: "weekend-freeze", description: "Memory snapshot", createdAt: Date.UTC(2026, 8, 1, 18, 0), parentId: "sn-gl-1" },
      { id: "sn-gl-3", name: "post-restore-test", description: "", createdAt: Date.UTC(2026, 8, 2, 9, 12), parentId: "sn-gl-1" },
    ],
    currentSnapshotId: "sn-gl-2",
  }),
  vm({
    id: "vm-jump",
    name: "jumpbox",
    guestOs: "Ubuntu Linux (64-bit)",
    family: "linux",
    hostId: "h4",
    clusterId: "cl-lab",
    datastoreId: "ds-lab",
    networkId: "net-mgmt",
    cpu: 2,
    memoryMb: 2048,
    diskGb: 32,
    state: "poweredOn",
    ip: "10.10.10.20",
    tools: "running",
    cpuUsage: 6,
    memUsage: 31,
    uptimeSec: 86400 * 4,
    notes: "Bastion. MFA required.",
    folder: "Lab",
    mac: "00:50:56:b4:10:20",
  }),
  vm({
    id: "vm-fw",
    name: "edge-fw-01",
    guestOs: "FreeBSD 14 (64-bit)",
    family: "other",
    hostId: "h4",
    clusterId: "cl-lab",
    datastoreId: "ds-lab",
    networkId: "net-dmz",
    cpu: 2,
    memoryMb: 4096,
    diskGb: 16,
    state: "poweredOn",
    ip: "10.40.1.1",
    tools: "running",
    cpuUsage: 9,
    memUsage: 22,
    uptimeSec: 86400 * 9,
    notes: "Lab edge firewall.",
    folder: "Lab",
    mac: "00:50:56:b4:40:01",
  }),
  vm({
    id: "vm-alpine",
    name: "alpine-test",
    guestOs: "Other 3.x or later Linux (64-bit)",
    family: "linux",
    hostId: "h4",
    clusterId: "cl-lab",
    datastoreId: "ds-lab",
    networkId: "net-vm",
    cpu: 1,
    memoryMb: 1024,
    diskGb: 8,
    state: "poweredOff",
    ip: null,
    tools: "notRunning",
    cpuUsage: 0,
    memUsage: 0,
    uptimeSec: 0,
    notes: "Scratch VM for ISO tests.",
    folder: "Lab",
    mac: "00:50:56:b4:00:08",
  }),
  vm({
    id: "vm-win-dev",
    name: "win-dev-01",
    guestOs: "Microsoft Windows 11 (64-bit)",
    family: "windows",
    hostId: "h4",
    clusterId: "cl-lab",
    datastoreId: "ds-lab",
    networkId: "net-vm",
    cpu: 4,
    memoryMb: 8192,
    diskGb: 80,
    state: "poweredOff",
    ip: null,
    tools: "notInstalled",
    cpuUsage: 0,
    memUsage: 0,
    uptimeSec: 0,
    notes: "Developer desktop pool seed.",
    folder: "Lab",
    mac: "00:50:56:b4:11:01",
  }),
];

export const seedAlerts: AlertItem[] = [
  {
    id: "al-1",
    level: "warning",
    title: "vsanDatastore space",
    body: "Capacity used is 63%. Consider adding a disk group before 75%.",
    objectId: "ds-vsan",
    objectKind: "datastore",
  },
  {
    id: "al-2",
    level: "info",
    title: "gitlab-01 suspended",
    body: "Virtual machine has been suspended for 2 days. Resume or power off to free host memory.",
    objectId: "vm-gitlab",
    objectKind: "vm",
  },
  {
    id: "al-3",
    level: "warning",
    title: "Snapshot chain on gitlab-01",
    body: "3 snapshots present. Long chains slow storage and complicate backup.",
    objectId: "vm-gitlab",
    objectKind: "vm",
  },
];

export const defaultExpanded: Record<string, boolean> = {
  dc: true,
  "cl-prod": true,
  "cl-lab": true,
  h1: true,
  h2: true,
  h3: false,
  h4: true,
  folders: true,
  "folder-Production": true,
  "folder-Lab": true,
};
